// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract DoNothing{
    /*
    Non-payable

    gas	                24362 gas
    transaction cost	21184 gas 
    execution cost	    120 gas 

    Op-code in case non-payable

    .code
      PUSH 80			contract DoNothing{\n    /*\n ...
      PUSH 40			contract DoNothing{\n    /*\n ...
      MSTORE 			contract DoNothing{\n    /*\n ...
      CALLVALUE 			contract DoNothing{\n    /*\n ...
      DUP1 			contract DoNothing{\n    /*\n ...
      ISZERO 			contract DoNothing{\n    /*\n ...
      PUSH [tag] 1			contract DoNothing{\n    /*\n ...
      JUMPI 			contract DoNothing{\n    /*\n ...
      PUSH 0			contract DoNothing{\n    /*\n ...
      DUP1 			contract DoNothing{\n    /*\n ...
      REVERT 			contract DoNothing{\n    /*\n ...
    tag 1			contract DoNothing{\n    /*\n ...
      JUMPDEST 			contract DoNothing{\n    /*\n ...
      POP 			contract DoNothing{\n    /*\n ...
      PUSH 4			contract DoNothing{\n    /*\n ...
      CALLDATASIZE 			contract DoNothing{\n    /*\n ...
      LT 			contract DoNothing{\n    /*\n ...
      PUSH [tag] 2			contract DoNothing{\n    /*\n ...
      JUMPI 			contract DoNothing{\n    /*\n ...
      PUSH 0			contract DoNothing{\n    /*\n ...
      CALLDATALOAD 			contract DoNothing{\n    /*\n ...
      PUSH E0			contract DoNothing{\n    /*\n ...
      SHR 			contract DoNothing{\n    /*\n ...
      DUP1 			contract DoNothing{\n    /*\n ...
      PUSH ED8FD55C			contract DoNothing{\n    /*\n ...
      EQ 			contract DoNothing{\n    /*\n ...
      PUSH [tag] 3			contract DoNothing{\n    /*\n ...
      JUMPI 			contract DoNothing{\n    /*\n ...
    tag 2			contract DoNothing{\n    /*\n ...
      JUMPDEST 			contract DoNothing{\n    /*\n ...
      PUSH 0			contract DoNothing{\n    /*\n ...
      DUP1 			contract DoNothing{\n    /*\n ...
      REVERT 			contract DoNothing{\n    /*\n ...
    tag 3			function doNothingV1()external...
      JUMPDEST 			function doNothingV1()external...
      STOP 			function doNothingV1()external...
    .data

====================================================================

    Payable

    gas                 24309 gas
    transaction cost	21138 gas 
    execution cost      74 gas

    Op-code in case payable

    .code
        PUSH 80			contract DoNothing{\n    /*\n ...
        PUSH 40			contract DoNothing{\n    /*\n ...
        MSTORE 			contract DoNothing{\n    /*\n ...
        PUSH 4			contract DoNothing{\n    /*\n ...
        CALLDATASIZE 			contract DoNothing{\n    /*\n ...
        LT 			contract DoNothing{\n    /*\n ...
        PUSH [tag] 1			contract DoNothing{\n    /*\n ...
        JUMPI 			contract DoNothing{\n    /*\n ...
        PUSH 0			contract DoNothing{\n    /*\n ...
        CALLDATALOAD 			contract DoNothing{\n    /*\n ...
        PUSH E0			contract DoNothing{\n    /*\n ...
        SHR 			contract DoNothing{\n    /*\n ...
        DUP1 			contract DoNothing{\n    /*\n ...
        PUSH 2F576F20			contract DoNothing{\n    /*\n ...
        EQ 			contract DoNothing{\n    /*\n ...
        PUSH [tag] 2			contract DoNothing{\n    /*\n ...
        JUMPI 			contract DoNothing{\n    /*\n ...
        tag 1			contract DoNothing{\n    /*\n ...
        JUMPDEST 			contract DoNothing{\n    /*\n ...
        PUSH 0			contract DoNothing{\n    /*\n ...
        DUP1 			contract DoNothing{\n    /*\n ...
        REVERT 			contract DoNothing{\n    /*\n ...
        tag 2			function doNothing()external p...
        JUMPDEST 			function doNothing()external p...
        STOP 			function doNothing()external p...
        .data


    Payble function are cheaper than Non-Payable funciton
    
    */
    function doNothing()external payable {

    }

}